# Remember to set workflow permission to read and write!

on:
    pull_request:
        types:
            - closed
        branches:
            - main

jobs:
    on_merge:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
        - name: Pull repo
          uses: actions/checkout@v2
          with:
            ref: main
        - name: Bump beta version
          run: ./.github/workflows/bumper.sh ./package/version.txt # Set this script and version file directories
        - name: Commit and push
          run: |
              git config user.name github-actions
              git config user.email github-actions@github.com
              git commit -a -m "[AUTO] Bump beta version number"
              git push --force-with-lease
    
